### ISSUE TITLE
Consider renaming the starter

### ISSUE THREAD

**Issue by snicoll** [mkopylec/charon-spring-boot-starter#1]
https://github.com/spring-projects/spring-boot/pull/6117 requests to include this starter in the list of 3rd party starters so I had a quick look to it. 

Could you please consider renaming this project into something less generic? A code name of some kind rather than "reverse-proxy" would be good. The positive side effect is that the root group for configuration key would be a single word (rather than `reverse-proxy` which is quite unusual).

**Comment by mkopylec** [comment]
Renamed to Charon
