### ISSUE TITLE
Allow manual mappings update

### ISSUE THREAD

**Issue by ludoo0d0a** [mkopylec/charon-spring-boot-starter#10]
It would be great to have a manual entry to update mappings, not only when request failed.
In a case where MappingsProvider would be updated externally (updated properties file, or DB storage)

Anyway, nice project. I hope to see more features later ;)

**Comment by mkopylec** [comment]
Hi, I am not sure what do mean.
Could you please provide more details and/or maybe a sample code?

What do you mean by "manual"? Would you like to have a feature that allows you to update mappings using JMX?

**Comment by ludoo0d0a** [comment]
I'd like to update mappings without restarting app (live update). Once updated, I need a method to call this update.

But after digging into your code, it seems it is already feasible since beans are optional (well done :)
I test a version where I set my own MappingsProvider and I can call 'updateMappings' on it.

**Comment by mkopylec** [comment]
Yes, you can call `updateMappings()` from your application code whenever you want.
This call will update the mappings according to your `MappingsProvider` implementation.
Let me know if this is OK for you. If so I the issue should be closed.

**Comment by ludoo0d0a** [comment]
Finished a first version.
It works fine ! Thanks.

**Comment by mkopylec** [comment]
Great :)
