### ISSUE TITLE
Do not treat /path and /path/something as duplicated mappings.

### ISSUE THREAD

**Issue by mkopylec** [mkopylec/charon-spring-boot-starter#13]
request to /path/* -> mapped to /path
request to /path/something/* -> mapped to /path/something

**Comment by matheusmessora** [comment]
@mkopylec I'm doing some work on this issue. Trying to help.

I ordered the mappings from the more context-specific first (like /uri/context/a comes first when compared to /uri/context).
When the "resolvedMappings" are found, the first one is returned.

**Comment by mkopylec** [comment]
Done
