### ISSUE TITLE
HttpRequestMapper sets an empty byte array body in case of GET requests

### ISSUE THREAD

**Issue by aricang** [mkopylec/charon-spring-boot-starter#133]
extractBody method of HttpRequestMapper is setting an empty body for GET requests which leads to wrong MessageConverter(ByteArrayHttpMessageConverter) selection in Rest Template.  This message converter adds "content-type:application/octet-stream" to every delegated get request, although get requests do not have any message body.

**Comment by mkopylec** [comment]
Resolved in 5.2.0

**Comment by goarican** [comment]
thank you very much for the fix
