### ISSUE TITLE
Multipart file uploads supported?

### ISSUE THREAD

**Issue by joerwin** [mkopylec/charon-spring-boot-starter#34]
I am trying to utilize your proxy implementation to add a security layer between my UI and multiple backend REST services. I have been able to handle all OPTIONS requests as well as all GET requests. I am wondering how to manage proxying a Multipart file upload POST request.

I have found that your implementation utilises the Netty4ClientHttpRequestFactory wich in its documentation indicates "this implementation consistently closes the HTTP connection on each request". So I have overridden the HttpClientProvider to utilize the HttpComponentsAsyncClientHttpRequestFactory instead to allow for keep alive connections.

We have an HAProxy instance between my implementation and the actual REST services. Becuase the security layer has its own DNS host name entry I have also overridden the ReverseProxyFilter.addForwardHeaders to set the HOST header correctly (from the mappingProperties) so that the host name HAPRoxy ACLs will function correctly.

The service I am proxying my requests to continues to return a 400 BAD Request response to my requests die to the body not containing the boundry.

is there special configuration required to handle mutlipart file uploads?

**Comment by mkopylec** [comment]
Hi, the newest version of Charon uses Apache HTTP client for forwarding requests: https://github.com/mkopylec/charon-spring-boot-starter/blob/master/src/main/java/com/github/mkopylec/charon/core/http/HttpClientProvider.java
I haven't tested multipart file uploads, maybe try something like: https://stackoverflow.com/questions/7003045/attempting-to-test-rest-service-with-multipart-file
Maybe you are sending an incorrect HTTP request or the receiving service behind the HAProxy is incorrectly configured.
Let me know if you have found any solution for that.

**Comment by joerwin** [comment]
I ended up identifying a couple of issues.
I was using spring and it was inserting the HiddenHttpMethodFilter into the filter chain and this was invalidating the input stream and causing the body forwarded to be empty which was causing bad requests. 
The next issue that I had to solve was that the restTemplate exchange would read in the entire file part into memory causing OOM issues in my proxy. To remedy this I check the request to see if it is multipart (ServletFileUpload.isMultipartContent(httpServletRequest)) and then I manage the multipart myself using an HttpUrlConnection. This allowed me to write directly to the output stream of the open connection keeping memory consumption reasonable.

            httpConn.setRequestProperty("Transfer-Encoding","chunked");
            httpConn.setChunkedStreamingMode(1);
            httpConn.connect();
            
            IOUtils.copy(request.getInputStream(), httpConn.getOutputStream());

**Comment by mkopylec** [comment]
Interesting topic.
Remember that `HttpUrlConnection` does not support timeouts by itself and you must implement timeouts yourself. If you don't your app can even crash if the latency will increase. This is because HTTP connections will hang for a long time increasing RAM and file descriptors usage.
