### ISSUE TITLE
Is there a way how to add custom headers for proxied requests?

### ISSUE THREAD

**Issue by dmarko484** [mkopylec/charon-spring-boot-starter#40]
We would like to integrate Grafana using 'authproxy' feature with our SpringBoot app see https://grafana.com/blog/2015/12/07/grafana-authproxy-have-it-your-way/ ... to share authentication Grafana requires custom header (X-WEBAUTH-USER) to be forwarder with proxied request. Is there a way how to add custom header like this?

**Comment by mkopylec** [comment]
Hi, Charon proxies the whole requests, including HTTP headers, so you can add the authentication header to the request that must be proxied by Charon.
Currently there is no support for adding custom headers to the forwarded request.
Let me know if you definitely need such a feature and I will implement it.

**Comment by dmarko484** [comment]
Thanks for info. my scenario is like this:

- user is working with my SpringBoot app as an authenticated
- I configure Charon to work as reverse proxy to Grafana
- to help Grafana understand who user is, I need to add 'X-WEBAUTH-USER' header with spring boot auth info into each request forwarded to Grafana

You say "Charon proxies the whole requests, including HTTP headers, so you can add the authentication header to the request that must be proxied by Charon." ... How can I do it prior request is proxied to backround service(Grafana)?

**Comment by mkopylec** [comment]
Ok, I understand now, you need a support for adding custom headers on Charon level.
There is no such feature for now, I will implement it and let you know.

**Comment by dmarko484** [comment]
Unbelievable ... Thanks!

**Comment by mkopylec** [comment]
Please close the issue if your problem is solved now.

**Comment by dmarko484** [comment]
It's working great! Thanks a lot!
