### ISSUE TITLE
Unable to start Charon due to problem with dual ServerProperties bean

### ISSUE THREAD

**Issue by jecuendet** [mkopylec/charon-spring-boot-starter#50]
We have an application embedding Spring Cloud Zuul (Intelligent microservices reverse proxy)
If we add Charon to this application, it'won't start anymore. It fail with the error:

 `
***************************
APPLICATION FAILED TO START
***************************
Description:
Field server in com.github.mkopylec.charon.configuration.CharonConfiguration required a single bean, but 2 were found:
	- serverProperties: defined by method 'serverProperties' in org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration
	- server-org.springframework.boot.autoconfigure.web.ServerProperties: defined in null
`

We have workaround it by excluding CharonConfiguration 
`
@SpringBootApplication(exclude = {CharonConfiguration.class})
`
And adding our copy-paste version, while removing ServerProperties here:
`@EnableConfigurationProperties({CharonProperties.class})`

**Comment by mkopylec** [comment]
Fixed in 2.4.0
