### ISSUE TITLE
Update to spring-boot 2.0 

### ISSUE THREAD

**Issue by torsten-liermann** [mkopylec/charon-spring-boot-starter#58]
Hi,

Is it possible to update this project to spring-boot 2.0?

Here are my changes for spring-boot 2.0.1 The groovy test still needs to be corrected. Note: @Qualified and name are not necessary if the factory method is named accordingly.

[migrateToSpringBoot201.patch.txt](https://github.com/mkopylec/charon-spring-boot-starter/files/2019368/migrateToSpringBoot201.patch.txt)

Thanks,
Torsten

**Comment by mkopylec** [comment]
Please create a pull request that contains your changes

**Comment by torsten-liermann** [comment]
The pull request: https://github.com/mkopylec/charon-spring-boot-starter/pull/60
(Over a week ago I wrote to your o2.pl address.)

**Comment by mkopylec** [comment]
Done, try version 3.0.0

**Comment by torsten-liermann** [comment]
Thanks!

Please note: I do not know anything about gradle.

Running gradlew test, I get the following error: 

```
com.github.mkopylec.charon.specification.TracingSpec > Should capture trace while proxying HTTP request when matching mapping exists and URI is /uri/1/sync FAILED
    com.github.tomakehurst.wiremock.client.VerificationException

com.github.tomakehurst.wiremock.client.VerificationException: A request was unmatched by any stub mapping. Closest stub mapping was:  expected:<
GET
/path/7
> but was:<
GET
/path/7
>
	at com.github.tomakehurst.wiremock.client.VerificationException.forSingleUnmatchedRequest(VerificationException.java:43)
	at com.github.tomakehurst.wiremock.client.VerificationException.forUnmatchedNearMisses(VerificationException.java:48)
	at com.github.tomakehurst.wiremock.junit.WireMockRule.checkForUnmatchedRequests(WireMockRule.java:92)
```

It is more elegant to import dependency management from spring-boot (org.springframework.boot: spring-boot-dependencies) for dependencies like spring-retry, httpclient, micrometer, commons-lang3.

For future versions of spring-boot, it would be more practical if the spring-boot dependencies are 'optional' or 'provided' (maven jargon) and so do not get into the projects as transitive dependencies.

**Comment by mkopylec** [comment]
Thanks for advice.
All tests have pass locally on my machine and on travis CI, it's strange why they failed when you run them.

**Comment by torsten-liermann** [comment]
This test works for me on Linux, but not on Windows 10 with the same jdk (1.8.0_171)
