### ISSUE TITLE
how to ignore SSL

### ISSUE THREAD

**Issue by dddyHD** [mkopylec/charon-spring-boot-starter#64]
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by dddyHD** [comment]
https://localhost:8443 ,I have a local project, but there is no certificate

**Comment by mkopylec** [comment]
You can't request the host with SSL (https) when the host's server is lack of certificate.
First configure SSL on the localhost server and then try requesting it by charon.

**Comment by mkopylec** [comment]
Is the issue still valid?

**Comment by mkopylec** [comment]
Closing it because of no response
