### ISSUE TITLE
Disable Cookie Management in HttpClient provider

### ISSUE THREAD

**Issue by jecuendet** [mkopylec/charon-spring-boot-starter#69]
Don't stock the cookies that are sent between the client and the browser
This can cause a lot of problems around mixing Sessions between HTTP connections
This can lead to Session steal from a user to another!
Hint: Spring Cloud Hystrix also disables it by default

**Comment by jecuendet** [comment]
After merge, please backport to 2.6.x branch and release a version against spring-boot 1.5.x

**Comment by mkopylec** [comment]
I not sure if this should be the default behaviour.
If you'd like to customize the http client you can do it on your own by extending `HttpClientProvider` Srping bean.

**Comment by jecuendet** [comment]
In Spring Cloud, it's disabled by default
See:
RibbonLoadBalancingHttpClient
HttpClientFeignLoadBalancedConfiguration
DefaultApacheHttpClientFactory

Look for
disableCookieManagement

IMO, this is a better default to disable it...

**Comment by mkopylec** [comment]
Hi, the new version of Charon will expose a cookie rewriting configuration so you will be able to configure how cookies have to be handled:
 - do not inculde cookies in outgoing response
 - include cookies in outgoing response and rewrite its server to client host and path to /
 - custom behaviour

**Comment by mkopylec** [comment]
The 4.0.0 is out and it provides configurable cookies handling.
