### ISSUE TITLE
Charon v4

### ISSUE THREAD

**Issue by mkopylec** [mkopylec/charon-spring-boot-starter#79]
I'm planning to completely rewrite Charon. The new version will:
 - support webmvc and webflux
 - add [resilience4j](https://github.com/resilience4j/resilience4j) support for forwarding process, configured globally and per mapping
 - remove yml configuration in favour of code configuration
 - remove any interceptor/tracing interfaces in favour of one interceptor that can be set globally or per mapping
 - remove path stripping feature in favour of explicitly declared destination path (maybe some sort of path rewritting mechanism)
 - try to include unresolved issues solutions
 - maybe more...

Stay tuned.

**Comment by robmoore** [comment]
Not sure if this is the right place to ask but would it be possible to add the ability to ignore particular paths or to allow for specifying multiple paths that all are directed to the same destination?

**Comment by mkopylec** [comment]
There will be a path rewrite based on regex groups implemented so it will be possible to map several incomming paths to one outgoing path.
As for ignoring certain paths I could implement such a thing as a global setting in Charon's configuration.

So yes, it should all be included in the new version.

**Comment by mkopylec** [comment]
The 4.0.0 version has been released
