### ISSUE TITLE
Can mapping have an exclusion property?

### ISSUE THREAD

**Issue by lcx-seima** [mkopylec/charon-spring-boot-starter#81]
I noticed code [here](https://github.com/mkopylec/charon-spring-boot-starter/blob/master/src/main/java/com/github/mkopylec/charon/core/mappings/MappingsProvider.java#L44-L46) is to resolve mapping by matching uri prefix.
In some case, I made reverse-proxy under path `/some/path`, but I still want some of sub-paths don't obey the proxy rules.
In this way, path like `/some/path/not/be/proxy` still can be handled by my application.

thanks.

**Comment by mkopylec** [comment]
Hi, in version 4.0.0 there will be a path rewrite mechanism based on regex groups, so it will be possible to handle your case.
I am no longer developing to 3.x.x version, if you need this fix in 3.x.x please provide a pull request.

**Comment by mkopylec** [comment]
This can be done in 4.0.0 by setting the right regex in request path rewriter.
