### ISSUE TITLE
Error creating bean with name 'charonReverseProxyFilterRegistrationBean'

### ISSUE THREAD

**Issue by Jacuo** [mkopylec/charon-spring-boot-starter#9]
When I tried to use charon sproing boot starter I have an error

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'charonReverseProxyFilterRegistrationBean' defined in class 
..........................................
[org.springframework.web.client.RestOperations]: No qualifying bean of type [org.springframework.web.client.RestOperations] found for dependency: expected at least 1 bean which qual
ifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Qualifier(value=charonRestOperations)}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type
 [org.springframework.web.client.RestOperations] found for dependency: expected at least 1 bean

**Comment by mkopylec** [comment]
Hi, this is quite strange.
Can you provide some more code to analize?
Please make sure you have added `@EnableCharon` to your Spring Boot application root class.
Also check if you are using the latest version of Charon which is 1.4.2
