### ISSUE TITLE
how to work with spring security

### ISSUE THREAD

**Issue by 554943871** [mkopylec/charon-spring-boot-starter#93]
I found that charon-proxy ignore the spring security filter , charon has higher priority than spring security filter, I need to protect the url which will be proxied with spring security.

**Comment by mkopylec** [comment]
The order of the Charon’s filter is configurable

**Comment by mkopylec** [comment]
Do you still have a problem with that?

**Comment by torsten-liermann** [comment]
I have a problem with this, because I use a jsr196 approach. How can I configure the order of the Charon's filters?

Thanks

**Comment by mkopylec** [comment]
```
@Configuration
class CharonConfiguration {

    @Bean
    CharonConfigurer charonConfigurer() {
        return charonConfiguration().filterOrder(<int>);
    }
}
```
By default it's set to `Ordered.HIGHEST_PRECEDENCE`.

**Comment by 554943871** [comment]
Thank you very much!

**Comment by mkopylec** [comment]
No problem.
PS: Maybe you don't need Spring Security in your app. Charon supports basic and bearer HTTP authentication schemes. See [here](https://github.com/mkopylec/charon-spring-boot-starter/wiki/Request-forwarding-interceptors#basic-authenticator).
