### ISSUE TITLE
Missing migration guide

### ISSUE THREAD

**Issue by torsten-liermann** [mkopylec/charon-spring-boot-starter#94]
Hi,

a little migration guide would be nice.
Coming from version 3.20, I have no idea for fixing these compile errors without studying the entire documentation and source code.
A spring boot starter with autoconfiguration of webmvc and webflux would also be handy.

![image](https://user-images.githubusercontent.com/1811740/61992434-c0d35300-b05e-11e9-98c0-613e68c0df43.png)

Thanks,
Torsten

**Comment by mkopylec** [comment]
It will be hard to create such a migration guide because all that has left from the old version is the name: Charon. The new Charon is a completely new project with a new way for configuring featuresa and some new features added. The webmvc and webflux versions have identical configuration APIs.

**Comment by torsten-liermann** [comment]
This is a pity that absolutely no configuration options exist. Often, mappings must be customizable using external configuration. Unfortunately, charon proxy does not follow the idea of spring boot regarding externalized configuration. Each application now has to implement MappingProperties and so on. Not so good. Is it planned for future releases?

**Comment by mkopylec** [comment]
I need to understand more what problem you are trying to solve.
Do you need a possibility to change request mappings during application runtime?

**Comment by reecefenwick** [comment]
Agreed with @torsten-liermann, removing the configuration property support has significantly increased the complexity involved in using this library

What the motivation was for this change?

**Comment by mkopylec** [comment]
Hi @reecefenwick this is why I've changed it:
1. IDE does not support code completion in YML files if there is a `List` or `Map` property in `@ConfigurationProperties` class.
2. `@ConfigurationProperties` allows only to configure simple properties like `String`, `int`, `Duration`, `Class` etc. It is hard to model configuration for nested objects like the `LoadBalancer` [here](https://github.com/mkopylec/charon-spring-boot-starter/blob/master/charon-common/src/main/java/com/github/mkopylec/charon/forwarding/interceptors/rewrite/CommonRequestServerNameRewriter.java#L24) or `List<ClientHttpRequestInterceptor>` [here](https://github.com/mkopylec/charon-spring-boot-starter/blob/master/charon-spring-webmvc/src/main/java/com/github/mkopylec/charon/forwarding/RestTemplateConfiguration.java#L22)
3. Custom features (forwarding interceptors) can now use the same configuration API/style as the available ones.

**Comment by mkopylec** [comment]
If you still need help, let me know.
