### ISSUE TITLE
class not found ？？？

### ISSUE THREAD

**Issue by siqiniao** [mkopylec/charon-spring-boot-starter#95]
![image](https://user-images.githubusercontent.com/2796825/62957147-cd112b80-be26-11e9-87c8-aafced4548af.png)

**Comment by mkopylec** [comment]
This is not possible.
[Here](https://github.com/mkopylec/charon-spring-boot-starter/tree/master/charon-spring-webmvc/src/main/java/com/github/mkopylec/charon/configuration) are the classes from webflux module and [here](https://github.com/mkopylec/charon-spring-boot-starter/tree/master/charon-spring-webmvc/src/main/java/com/github/mkopylec/charon/configuration) from webmvc module.
Your name is wrong. _CharonConfigurer.java_ does not match the class name defined the file: `CharonConfiguration`.

**Comment by mkopylec** [comment]
If you still need help, let me know.
