### ISSUE TITLE
Problem with missing form parameters when using Charon reverse proxy after passing other filters

### ISSUE THREAD

**Issue by HweiH** [mkopylec/charon-spring-boot-starter#98]
Problem with missing form parameters when using Charon reverse proxy after passing other filters. 
It is possible that other filters read data from the Request Body, such as Spring Boot, which caused Charon to no longer get parameters from the Request Body. Hope to add extractParameters method to Charon's HttpRequestMapper :)

**Comment by HweiH** [comment]
@mkopylec @RichardBradley @cezarykluczynski

**Comment by mkopylec** [comment]
Hi @HweiH 
Charon's filter is invoked before any other filters by default, so it should read form parameters without any problem.
Have you changed the filter's order?
What version of and module of Charon do you use?
Can you provide some sample code?

**Comment by HweiH** [comment]
Yes, I changed the order of Charon's reverse proxy filters. I put it behind the Spring Security filter chain.
I am using Charon v4.3.0 and it is a WebMVC module.
For the sample code, you can refer to the extractBody method of the HttpRequestMapper class in the source code.
In other words, when other filters use the request.getParameter method to obtain the parameters, then when the extractBody method is reached, the form parameters can no longer be read from the stream.
I hope Charon adds a method extractParameters to get the form parameters from the request when the extractBody method cannot get the byte data :)

**Comment by HweiH** [comment]
Maybe the code below helps:
![1575438671527](https://user-images.githubusercontent.com/9005272/70116309-4fa34c80-169d-11ea-8c0f-334d6183245f.jpg)

**Comment by HweiH** [comment]
Maybe the code below helps:

![1575438671527](https://user-images.githubusercontent.com/9005272/70116364-78c3dd00-169d-11ea-949d-a58f757fdca7.jpg)

**Comment by mkopylec** [comment]
The `request.getParameter(...)` method can also obtain a URL query param, which doesn't belong to request body.
The code you wrote must be smarter.
I'll think about it and let you know

**Comment by mkopylec** [comment]
Maybe wrapping request with `HttpServletRequestWrapper` and caching the body can be a valid solution.

**Comment by mkopylec** [comment]
Is Charon's authentication support not enough for your needs?
You can use [basic authentication](https://github.com/mkopylec/charon-spring-boot-starter/wiki/Request-forwarding-interceptors#basic-authenticator) or [bearer](https://github.com/mkopylec/charon-spring-boot-starter/wiki/Request-forwarding-interceptors#bearer-authenticator) one.

**Comment by HweiH** [comment]
Yes, that's just my sample code. My final solution is to solve this problem by inheriting the ReverseProxyFilter class and rewriting the doFilterInternal() method, and using the HttpServletRequestWrapper class to wrap the request.
Thank you very much for your attention.
I hope Charon will be smarter and powerful when integrated with the Spring framework.
I only use Spring Security as a security framework for authentication and authorization.

**Comment by mkopylec** [comment]
Why do you need to override the `ReverseProxyFilter`?
You can add a new filter before any other filter which will wrap the request with Spring's `ContentCachingRequestWrapper`.
That should resolve your issue.

Can you try the above solution?

**Comment by HweiH** [comment]
That's it, wrap the request before entering the doFilterInternal() method.
Your solution can also solve my problem, thanks.
After a while I will close this Issue.
