### ISSUE TITLE
Update to Spring Boot 2.2.x

### ISSUE THREAD

**Issue by sdavids13** [mkopylec/charon-spring-boot-starter#99]
We would like Charon to upgrade to Spring Boot 2.2 to avoid Spring versioning conflicts.

**Comment by mkopylec** [comment]
I tried to update all the dependencies but I am stuck with [this issue](https://github.com/resilience4j/resilience4j/issues/764)

**Comment by mkopylec** [comment]
Done in 4.5.0

**Comment by sdavids13** [comment]
Happen to know about how long it takes to propagate to [maven central](https://mvnrepository.com/artifact/com.github.mkopylec/charon-spring-webmvc)?

**Comment by mkopylec** [comment]
It takes quite long time to be visible on the maven central UI.
But it should be already available to dwonload as project dependency.

**Comment by mkopylec** [comment]
https://search.maven.org/artifact/com.github.mkopylec/charon-spring-webmvc
